### ISSUE TITLE
Add search box component

### ISSUE THREAD

**Issue by zsoltime** [codesect/cs01-team-grace-01#7]
Add search box component. It should have a required prop, `onSubmit` which is called on form submission. Please make sure, it's accessible. Use `form`, `label` with the text "Start by searching for a phone number", an `input` field, and a submit button. The placeholder can be "Type a phone number".

Please don't forget to add tests. Snapshot test is fine, but it would be great to check if the input field has a corresponding label and if the `onSubmit` prop is called on submit.

**Comment by bilalbutt044** [comment]
@zsoltime which library would be use for Snapshot testing ? I never write tests.

**Comment by zsoltime** [comment]
@bilalbutt044 Jest and Enzyme. We can talk about it on Discord ;)

**Comment by bilalbutt044** [comment]
@zsoltime  i am little confuse. what would be required prop for this search box component ? And in which component should i define  the function which will be called on `onSubmit`. `Home` or `SearchBox` component. Sorry dumb Question but it is making me confuse.

**Comment by zsoltime** [comment]
Only `onSubmit` is required, and it should receive the search query on form submit. 

You can add the search box on the home page to test it. Something like `<SearchBox onSubmit={console.log} />` should work.

I'll try to set up Enzyme and Cypress today for the tests.

**Comment by bilalbutt044** [comment]
@zsoltime i have develop SearchBox component. Now i have to write search query in GraphQl?

**Comment by zsoltime** [comment]
Solved in #12 and #17
